@startuml
!theme reddress-lightblue
participant Client
participant Backend
participant Database
participant ClientApp

Client -> Backend: sendPasswordResetRequest()
Backend -> Database: checkUserExistence()
Database --> Backend: userExist
Backend -> Backend: emailVerified = verifyEmail()

Backend --> Client: sendPasswordResetEmail() if emailVerified
Backend --> ClientApp: notifyUserInvalidEmail() if not emailVerified

ClientApp -> Backend: completePasswordResetRequest()
Backend -> Backend: tokenVerified = verifyToken()

Backend --> ClientApp: receiveLoginResponse() if tokenVerified
Backend --> ClientApp: notifyUserInvalidToken() if not tokenVerified
@enduml